server:
  port: 9527
spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/reggie?characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: qaz12345
    username: root
